version: "3"
#### Server
services:
  server:
    build: ./server
    expose:
      - ${SERVER_PORT}
    environment:
      MONGODB_URI: ${MONGODB_URI}
      SERVER_PORT: ${SERVER_PORT}
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    volumes:
      - ./server:/srv/app/server
    command: yarn start

  #### Client
  client:
    build: ./client
    environment:
      - CLIENT_PORT=${CLIENT_PORT}
    expose:
      - ${CLIENT_PORT}
    ports:
      - ${CLIENT_PORT}:${CLIENT_PORT}
    volumes:
      - ./client/src:/srv/app/client/src
      - ./client/src:/srv/app/client/build
    links:
      - server
    command: yarn start
